import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/header";

  const listProgramming = [
    { 
      name: "Programming",
      url: "/programming"
    },
    {
      name: "Sistemas Operacionais",
      url: "/"
    },
    {
      name: "Navegadores",
      url: "/"
    },
    {
      name: "Softwares",
      url: "/"
    }
  ];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Open Helper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header variant="primary" links={listProgramming} />
        <div className="lg:container lg:mx-auto lg:px-4">
          {children}
        </div>
      </body>
    </html>
  );
}
